version: '3'

services:

  php:
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/srv/www/salary_service
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - pgsql
      - redis
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  nginx:
    image: nginx:1.17.2
    ports:
      - 80:80
    volumes:
      - ./:/srv/www/salary_service
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

#  mysql:
#    image: mysql:5.7
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  pgsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - /home/alexkim/work/data/salary_service_pgsql:/var/lib/postgresql/data
    ports:
      - 5432:5432





  redis:
    image: redis
    ports:
    - 6379:6379